server:
  port: 3001

spring:
  profiles:
    active: dev

  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@${db.host}:${db.port}:orcl
    username: ${db.username}
    password: ${db.password}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddlAuto: create

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


jwt:
  header: Authorization # 명칭에 대한이름 -> 이 이름으로 토큰을 보내게 됨
  secret: ${jwt.secret} # base64 인코딩
  accessTokenValidityInSeconds: 3600 # 60 min


cors:
  origin: ${cors.origin}