spring:
  # 데이터 베이스 설정
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  # JPA 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.h2Dialect
        show_sql: true # sql 쿼리 보이게
        format_sql: true # 들여쓰기등 예쁘게 나옴 쿼리가...
        use_sql_comments: true
    hibernate:
      ddlAuto: create

# 로거 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace